import { Job, Research, Club, Course } from './types';

export const companies = [
  {
    id: '1',
    name: 'xAI',
    logo: 'https://img.logo.dev/xai.com?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Artificial intelligence research',
    industry: 'AI Research',
    matchScore: 95,
    valuation: '$45.0B',
    status: 'Private',
    jobCount: 156
  },
  {
    id: '2',
    name: 'Anthropic',
    logo: 'https://img.logo.dev/anthropic.com?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'AI systems and safety',
    industry: 'AI Safety',
    matchScore: 92,
    valuation: '$61.5B',
    status: 'Private',
    jobCount: 45
  },
  {
    id: '3',
    name: 'Perplexity AI',
    logo: 'https://img.logo.dev/perplexity.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Conversational AI platform',
    industry: 'AI Search',
    matchScore: 88,
    valuation: '$9.0B',
    status: 'Private',
    jobCount: 28
  },
  {
    id: '4',
    name: 'Mistral AI',
    logo: 'https://img.logo.dev/mistral.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Generative AI models',
    industry: 'AI/ML',
    matchScore: 86,
    valuation: '$6.2B',
    status: 'Private',
    jobCount: 42
  },
  {
    id: '5',
    name: 'Figure AI',
    logo: 'https://img.logo.dev/figure.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Humanoid robotics',
    industry: 'Robotics',
    matchScore: 84,
    valuation: '$2.7B',
    status: 'Private',
    jobCount: 89
  },
  {
    id: '6',
    name: 'Safe Superintelligence',
    logo: 'https://img.logo.dev/ssi.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Safe artificial intelligence',
    industry: 'AI Safety',
    matchScore: 82,
    valuation: '$5.0B',
    status: 'Private',
    jobCount: 34
  },
  {
    id: '7',
    name: 'Sierra',
    logo: 'https://img.logo.dev/sierra.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Enterprise AI',
    industry: 'AI/ML',
    matchScore: 80,
    valuation: '$4.5B',
    status: 'Private',
    jobCount: 67
  },
  {
    id: '8',
    name: 'The Bot Company',
    logo: 'https://img.logo.dev/thebotcompany.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Household robots',
    industry: 'Robotics',
    matchScore: 78,
    valuation: '$2.0B',
    status: 'Private',
    jobCount: 45
  },
  {
    id: '9',
    name: 'Cohere',
    logo: 'https://img.logo.dev/cohere.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Enterprise LLMs',
    industry: 'AI/ML',
    matchScore: 76,
    valuation: '$2.2B',
    status: 'Private',
    jobCount: 38
  },
  {
    id: '10',
    name: 'Inflection AI',
    logo: 'https://img.logo.dev/inflection.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'Personal AI assistants',
    industry: 'AI/ML',
    matchScore: 75,
    valuation: '$4.0B',
    status: 'Private',
    jobCount: 42
  },
  {
    id: '11',
    name: 'Scale AI',
    logo: 'https://img.logo.dev/scale.com?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'AI infrastructure',
    industry: 'AI/ML',
    matchScore: 74,
    valuation: '$7.3B',
    status: 'Private',
    jobCount: 89
  },
  {
    id: '12',
    name: 'Adept AI',
    logo: 'https://img.logo.dev/adept.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'AI agents and automation',
    industry: 'AI/ML',
    matchScore: 73,
    valuation: '$1.0B',
    status: 'Private',
    jobCount: 28
  },
  {
    id: '13',
    name: 'Character AI',
    logo: 'https://img.logo.dev/character.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ',
    description: 'AI characters and chat',
    industry: 'AI/ML',
    matchScore: 72,
    valuation: '$1.0B',
    status: 'Private',
    jobCount: 34
  }
];

export const jobs: Job[] = [
  {
    id: "job-001",
    title: "Senior ML Engineer",
    company: "OpenAI",
    location: "San Francisco, CA",
    remote: true,
    description: "Join our research team to develop and implement state-of-the-art machine learning algorithms to advance AI capabilities.",
    requirements: ["5+ years ML experience", "Strong Python & PyTorch", "PhD preferred"],
    categories: ["AI", "Machine Learning", "Research"],
    salary: "$200K - $350K",
    applicationDeadline: "2025-07-15",
    postedDate: "2025-05-01",
    skills: ["Python", "PyTorch", "ML", "Distributed Systems"],
    employmentType: "Full-time",
    experienceLevel: "Senior",
    logoUrl: "https://img.logo.dev/openai.com?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 95
  },
  {
    id: "job-002",
    title: "AI Safety Researcher",
    company: "Anthropic",
    location: "San Francisco, CA",
    remote: true,
    description: "Research and develop safe and ethical AI systems, focusing on alignment and robustness.",
    requirements: ["PhD in CS/ML", "Research experience", "Publications preferred"],
    categories: ["AI", "Safety", "Research"],
    salary: "$180K - $300K",
    applicationDeadline: "2025-06-30",
    postedDate: "2025-04-28",
    skills: ["Python", "ML", "AI Safety", "Research"],
    employmentType: "Full-time",
    experienceLevel: "PhD",
    logoUrl: "https://img.logo.dev/anthropic.com?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 92
  },
  {
    id: "job-003",
    title: "ML Platform Engineer",
    company: "Scale AI",
    location: "San Francisco, CA",
    remote: true,
    description: "Build and scale ML infrastructure for large-scale data processing and model training.",
    requirements: ["3+ years ML infra", "Strong systems design", "Cloud expertise"],
    categories: ["Infrastructure", "ML", "Platform"],
    salary: "$170K - $250K",
    applicationDeadline: "2025-06-15",
    postedDate: "2025-04-20",
    skills: ["Python", "Kubernetes", "AWS", "MLOps"],
    employmentType: "Full-time",
    experienceLevel: "Mid-Senior",
    logoUrl: "https://img.logo.dev/scale.com?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 88
  },
  {
    id: "job-004",
    title: "Research Engineer",
    company: "Cohere",
    location: "Toronto, Canada",
    remote: true,
    description: "Develop and improve large language models for enterprise applications.",
    requirements: ["ML expertise", "NLP background", "Distributed systems"],
    categories: ["AI", "NLP", "Research"],
    salary: "$160K - $240K",
    applicationDeadline: "2025-07-01",
    postedDate: "2025-04-15",
    skills: ["Python", "PyTorch", "NLP", "Transformers"],
    employmentType: "Full-time",
    experienceLevel: "Senior",
    logoUrl: "https://img.logo.dev/cohere.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 86
  },
  {
    id: "job-005",
    title: "Robotics Engineer",
    company: "Figure AI",
    location: "Sunnyvale, CA",
    remote: false,
    description: "Design and implement robotic control systems for humanoid robots.",
    requirements: ["Robotics experience", "Control systems", "C++"],
    categories: ["Robotics", "Control", "Hardware"],
    salary: "$150K - $230K",
    applicationDeadline: "2025-06-30",
    postedDate: "2025-04-10",
    skills: ["C++", "ROS", "Control Systems", "Python"],
    employmentType: "Full-time",
    experienceLevel: "Mid-Senior",
    logoUrl: "https://img.logo.dev/figure.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 84
  },
  {
    id: "job-006",
    title: "AI Research Scientist",
    company: "Inflection AI",
    location: "Palo Alto, CA",
    remote: true,
    description: "Research and develop next-generation AI models for personal assistance.",
    requirements: ["PhD in ML/AI", "Research experience", "Publications"],
    categories: ["AI", "Research", "NLP"],
    salary: "$180K - $280K",
    applicationDeadline: "2025-07-15",
    postedDate: "2025-04-05",
    skills: ["Python", "ML", "NLP", "Research"],
    employmentType: "Full-time",
    experienceLevel: "PhD",
    logoUrl: "https://img.logo.dev/inflection.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 82
  },
  {
    id: "job-007",
    title: "ML Infrastructure Engineer",
    company: "Perplexity AI",
    location: "San Francisco, CA",
    remote: true,
    description: "Build and maintain ML infrastructure for real-time search and question answering.",
    requirements: ["3+ years ML infra", "Distributed systems", "Cloud"],
    categories: ["Infrastructure", "ML", "Search"],
    salary: "$160K - $240K",
    applicationDeadline: "2025-06-30",
    postedDate: "2025-04-01",
    skills: ["Python", "Kubernetes", "AWS", "ML"],
    employmentType: "Full-time",
    experienceLevel: "Senior",
    logoUrl: "https://img.logo.dev/perplexity.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 80
  },
  {
    id: "job-008",
    title: "AI Safety Engineer",
    company: "Safe Superintelligence",
    location: "Berkeley, CA",
    remote: true,
    description: "Work on ensuring the safety and reliability of advanced AI systems.",
    requirements: ["ML background", "Safety expertise", "Research mindset"],
    categories: ["AI", "Safety", "Research"],
    salary: "$150K - $220K",
    applicationDeadline: "2025-07-01",
    postedDate: "2025-03-28",
    skills: ["Python", "ML", "AI Safety", "Research"],
    employmentType: "Full-time",
    experienceLevel: "Mid-Senior",
    logoUrl: "https://img.logo.dev/ssi.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 78
  },
  {
    id: "job-009",
    title: "Full Stack ML Engineer",
    company: "Character AI",
    location: "Palo Alto, CA",
    remote: true,
    description: "Build and deploy AI-powered character interactions and conversations.",
    requirements: ["Full stack experience", "ML knowledge", "React"],
    categories: ["Full Stack", "ML", "Web"],
    salary: "$140K - $210K",
    applicationDeadline: "2025-06-15",
    postedDate: "2025-03-25",
    skills: ["Python", "React", "TypeScript", "ML"],
    employmentType: "Full-time",
    experienceLevel: "Mid-Level",
    logoUrl: "https://img.logo.dev/character.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 76
  },
  {
    id: "job-010",
    title: "ML Ops Engineer",
    company: "Adept AI",
    location: "San Francisco, CA",
    remote: true,
    description: "Build and maintain ML deployment and monitoring infrastructure.",
    requirements: ["DevOps experience", "ML knowledge", "Monitoring"],
    categories: ["MLOps", "Infrastructure", "DevOps"],
    salary: "$140K - $200K",
    applicationDeadline: "2025-06-30",
    postedDate: "2025-03-20",
    skills: ["Python", "Kubernetes", "Prometheus", "ML"],
    employmentType: "Full-time",
    experienceLevel: "Mid-Level",
    logoUrl: "https://img.logo.dev/adept.ai?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ",
    matchScore: 74
  }
];

export const research: Research[] = [
  {
    id: "research-001",
    title: "Quantum Computing Research",
    institution: "Yale Quantum Institute",
    department: "Physics",
    professor: "Dr. Sarah Chen",
    location: "New Haven, CT",
    remote: false,
    description: "Research opportunity in quantum computing focusing on error correction and quantum algorithms.",
    requirements: ["Physics or Computer Science background", "Quantum mechanics knowledge", "Programming skills"],
    categories: ["Quantum Computing", "Physics", "Computer Science"],
    compensation: "$6,000 stipend",
    applicationDeadline: "2025-02-15",
    duration: "10 weeks",
    postedDate: "2024-12-01",
    skills: ["Quantum Computing", "Python", "Physics", "Mathematics"],
    logoUrl: "https://img.logo.dev/yale.edu?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ"
  }
];

export const clubs: Club[] = [
  {
    id: "club-001",
    name: "Yale Computer Society",
    university: "Yale University",
    category: "Technology",
    description: "Student organization focused on computer science, technology, and innovation through projects and events.",
    meetingSchedule: "Weekly, Thursdays at 7:00 PM",
    location: "Bass Library, Room 205",
    membershipRequirements: "Open to all students interested in technology",
    leadershipOpportunities: ["President", "Vice President", "Technical Lead", "Events Coordinator"],
    activities: ["Hackathons", "Tech Talks", "Workshops", "Project Teams"],
    contactEmail: "computer.society@yale.edu",
    socialMedia: {
      instagram: "@yalecompsci",
      discord: "YCS Discord",
      website: "yalecompsci.org"
    },
    tags: ["Programming", "Technology", "Innovation", "Computer Science"],
    logoUrl: "https://img.logo.dev/yale.edu?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ"
  }
];

export const courses: Course[] = [
  {
    id: "course-001",
    code: "CPSC 223",
    title: "Data Structures and Programming",
    department: "Computer Science",
    school: "Yale College",
    professor: "Dr. James Smith",
    term: "Spring 2025",
    schedule: "MWF 10:30 AM - 11:20 AM",
    location: "AKW 200",
    credits: 4,
    description: "Introduction to data structures, algorithms, and analysis. Programming in C++.",
    prerequisites: "CPSC 201 or equivalent programming experience",
    syllabus: "https://courses.yale.edu/cpsc223/syllabus",
    enrollmentCapacity: 200,
    currentEnrollment: 180,
    waitlist: 20,
    evaluationScore: 4.5,
    evaluationComments: [
      "Excellent foundation in data structures",
      "Challenging but rewarding",
      "Great preparation for technical interviews"
    ],
    tags: ["Computer Science", "Programming", "Algorithms", "C++"],
    logoUrl: "https://img.logo.dev/yale.edu?token=pk_VAZ6tvAVQHCDwKeaNRVyjQ"
  }
];